export const stages = [
    "Start",
    "Running 1",
    "1000m SkiErg",
    "Running 2",
    "50m Sled Push",
    "Running 3",
    "50m Sled Pull",
    "Running 4",
    "80m Burpee Broad Jump",
    "Running 5",
    "1000m Row",
    "Running 6",
    "200m Farmers Carry",
    "Running 7",
    "100m Sandbag Lunges",
    "Running 8",
    "Wall Balls",
    "Finish",
];

export const stationStageMap = {
    0: "station-start",
    1: "station-running1",
    2: "station-skierg",
    3: "station-running2",
    4: "station-sled-push",
    5: "station-running3",
    6: "station-sled-pull",
    7: "station-running4",
    8: "station-burpee-jumps",
    9: "station-running5",
    10: "station-row",
    11: "station-running6",
    12: "station-farmers-carry",
    13: "station-running7",
    14: "station-sandbag-lunges",
    15: "station-running8",
    16: "station-wallballs",
    17: "station-end",
};

export const completed = Array(stages.length).fill(0);
